//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.03.11 at 12:39:59 PM KST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.jcomdot.com/sqlmap", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.jcomdot.simplemvc.user.sqlservice.jaxb;
